apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worklenz.fullname" . }}-backend
  labels:
    {{ include "worklenz.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "worklenz.backendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "worklenz.labels" . | nindent 8 }}
        app.kubernetes.io/component: backend
        {{- with .Values.backend.podLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        {{ toYaml .Values.backend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-backend
          securityContext:
            {{ toYaml .Values.backend.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "worklenz.fullname" . }}-backend
            - secretRef:
                name: {{ include "worklenz.fullname" . }}-backend
          resources:
            {{ toYaml .Values.backend.resources | nindent 12 }}
