apiVersion: v1
kind: Secret
metadata:
  name: {{ include "worklenz.fullname" . }}-backend
  labels:
    {{- include "worklenz.labels" . | nindent 4 }}
type: Opaque
stringData:
  SESSION_SECRET: {{ .Values.backend.sessionSecret | quote }}
  COOKIE_SECRET: {{ .Values.backend.cookieSecret | quote }}

  GOOGLE_CLIENT_ID: {{ .Values.backend.googleClientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.backend.googleClientSecret | quote }}

  DB_USER: {{ .Values.backend.database.user | quote }}
  DB_PASSWORD: {{ .Values.backend.database.password | quote }}

  AWS_ACCESS_KEY_ID: {{ .Values.backend.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backend.awsSecretAccessKey | quote }}
  JWT_SECRET: {{ .Values.backend.jwtSecret | quote }}

  SLACK_WEBHOOK: {{ .Values.backend.slackWebhook | quote }}
