apiVersion: v1
kind: Secret
metadata:
  name: {{ include "worklenz.fullname" . }}-frontend
  labels:
    {{- include "worklenz.labels" . | nindent 4 }}
type: Opaque
data:
  VITE_MIXPANEL_TOKEN: {{ .Values.frontend.mixPanelToken | b64enc | quote }}
  VITE_RECAPTCHA_SITE_KEY: {{ .Values.frontend.reCaptchaSiteKey | b64enc | quote }}
  VITE_WORKLENZ_SESSION_ID: {{ .Values.frontend.sessionId | b64enc | quote }}
