apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worklenz.fullname" . }}-frontend
  labels:
    {{ include "worklenz.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "worklenz.frontendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "worklenz.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
        {{- with .Values.frontend.podLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        {{ toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-frontend
          securityContext:
            {{ toYaml .Values.frontend.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "worklenz.fullname" . }}-frontend
            - secretRef:
                name: {{ include "worklenz.fullname" . }}-frontend
          resources:
            {{ toYaml .Values.frontend.resources | nindent 12 }}
