apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "worklenz.fullname" . }}-frontend
  labels:
    {{- include "worklenz.labels" . | nindent 4 }}
data:
  VITE_API_URL: {{ (printf "https://%s" .Values.url.backend ) | quote }}
  VITE_SOCKET_URL: {{ (printf "wss://%s" .Values.url.backend ) | quote }}

  VITE_APP_TITLE: {{ .Values.frontend.appTitle | quote }}
  VITE_APP_ENV: {{ .Values.global.environment | quote }}

  VITE_ENABLE_RECAPTCHA: {{ .Values.frontend.reCaptchaEnabled | quote }}

