export const NotificationTypes = {
  NEW_TASK_ADDED: "NEW_TASK_ADDED",
  TASK_REMOVED: "TASK_REMOVED",
  ADDED_TO_A_PROJECT: "ADDED_TO_A_PROJECT",
  REMOVED_FROM_A_PROJECT: "REMOVED_FROM_A_PROJECT",
  MENTIONED_IN_A_TASK_COMMENT: "MENTIONED_IN_A_TASK_COMMENT",
  NEW_COMMENT_ADDED_TO_A_TASK: "NEW_COMMENT_ADDED_TO_A_TASK",
  TASK_TRANSITION: "TASK_TRANSITION",
  TASK_RENAME: "TASK_RENAME",
  TASK_ASSIGNMENT: "TASK_ASSIGNMENT",
  TASK_UNASSIGN: "TASK_UNASSIGN",
  ADD_TO_A_TEAM: "ADD_TO_A_TEAM",
  REMOVED_FROM_A_TEAM: "REMOVED_FROM_A_TEAM",
};
