import { DB_CONSTRAINS } from "../shared/constraints";

describe("constraints.ts", () => {
  it("should map the named active team constraint to a descriptive delete-team message", () => {
    expect(DB_CONSTRAINS.users_active_team_fk).toBe(
      "This team cannot be deleted because one or more users still have it selected as their active team. Please switch those users to another team and try again."
    );
  });

  it("should map the autogenerated active team constraint to the same descriptive delete-team message", () => {
    expect(DB_CONSTRAINS.users_active_team_fkey).toBe(DB_CONSTRAINS.users_active_team_fk);
  });

  it("should map the named project folders constraint to a descriptive delete-team message", () => {
    expect(DB_CONSTRAINS.project_folders_team_id_fk).toBe(
      "This team cannot be deleted because it still has project folders associated with it. Please remove those folders and try again."
    );
  });

  it("should map the autogenerated project folders constraint to the same descriptive delete-team message", () => {
    expect(DB_CONSTRAINS.project_folders_team_id_fkey).toBe(
      DB_CONSTRAINS.project_folders_team_id_fk
    );
  });
});
