// Centralized Ant Design imports for components and icons

// Components
export {
  Layout,
  Menu,
  Avatar,
  Dropdown,
  Badge,
  Button,
  theme,
  Card,
  Typography,
  Form,
  Input,
  Space,
  Flex,
  Checkbox,
  message,
  Alert,
  Tag,
  Divider,
  Select,
  Switch,
  ConfigProvider,
  Drawer,
  Table,
  Empty,
  Spin,
  Upload,
  Row,
  Col,
  Descriptions,
  Timeline,
  Statistic,
  Progress,
  Tooltip,
  Image,
  Popconfirm,
  List,
} from "antd/es";

// Types
export type { MenuProps } from "antd/es";

// Icons
export {
  DashboardOutlined,
  AppstoreOutlined,
  FileTextOutlined,
  ProjectOutlined,
  FileDoneOutlined,
  MessageOutlined,
  SettingOutlined,
  UserOutlined,
  BellOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  LogoutOutlined,
  MoonOutlined,
  SunOutlined,
  TranslationOutlined,
  RightOutlined,
  MenuOutlined,
  EyeOutlined,
  PlusOutlined,
  ArrowLeftOutlined,
  UploadOutlined,
  PaperClipOutlined,
  SendOutlined,
  MailOutlined, 
  PhoneOutlined,
  TeamOutlined,
  LockOutlined,
  SearchOutlined,
  CalendarOutlined,
  ShareAltOutlined,
  DeleteOutlined,
  DownloadOutlined,
  FileOutlined,
  FileImageOutlined,
  VideoCameraOutlined,
  FilePdfOutlined,
  CheckCircleOutlined,
  ClockCircleOutlined,
  DollarOutlined,
  ReloadOutlined,
  WarningOutlined,
  InfoCircleOutlined,
  ExclamationCircleOutlined,
} from "@ant-design/icons";
